name: build-and-publish
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Setup Python
        shell: bash
        run: uv python install

      - name: Install dependencies
        shell: bash
        run: uv sync --locked --all-extras --dev

      - name: Generate release filename
        shell: bash
        run: |
          RELEASE_NAME="$(python ./generate_release_filename.py)"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Build
        shell: bash
        run: uv run pyinstaller -F main.py -n ${{ env.RELEASE_NAME }} --add-data VERSION:.

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact-${{ strategy.job-index }}
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VERSION
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            VERSION
          sparse-checkout-cone-mode: false

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
          pattern: artifact-*
          merge-multiple: true

      - name: Read version
        shell: bash
        run: |
          RELEASE_VERSION="$(cat VERSION)"
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
          files: dist/*